version: '3.5'

services:
  clickhouse_test:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse_test
    hostname: clickhouse_test
    ports:
      - "8123:8123"
      - "9000:9000"
  vertica:
    image: jbfavre/vertica:latest
    container_name: vertica-perfomance-test
    hostname: vertica
    ports:
      - "5433:5433"